# Generated by Django 3.0 on 2021-12-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del objetivo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes_post')),
                ('estado', models.BooleanField(default=True, verbose_name='Objetivo Activado/No Activado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_post'),
        ),
        migrations.AddField(
            model_name='post',
            name='objetivo',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='post.Objetivo'),
            preserve_default=False,
        ),
    ]
