# Generated by Django 3.0 on 2021-12-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.IntegerField(null=True),
        ),
    ]
