# Generated by Django 3.0 on 2021-12-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comentarios',
            field=models.IntegerField(),
        ),
    ]
