# Generated by Django 3.0 on 2021-12-17 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comentarios',
        ),
    ]
