# Generated by Django 3.0 on 2021-12-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_auto_20211219_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetivo',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
    ]
