# Generated by Django 3.0 on 2021-12-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20211214_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='avatar.png', upload_to='img_perfil'),
        ),
    ]
