# Generated by Django 3.0 on 2021-12-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20211214_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='avatar.png', upload_to='img_perfil'),
        ),
    ]
