# Generated by Django 3.0 on 2021-12-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20211217_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='media/avatar.png', upload_to='img_perfil'),
        ),
    ]
